<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CreateBrandTest extends TestCase
{
    use RefreshDatabase;



    /** @test */
    public function un_usuario_autenticado_puede_crear_marcas()
    {
        $this->withoutExceptionHandling();

        $user = factory(User::class)->create();
        $this->actingAs($user);

        $this->post(url('admin/brands/create'),['name' => 'Soprole']);

        $this->assertDatabaseHas('brands', [
            'name' => 'Soprole'
        ]);
    }
    /*public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Route::prefix('admin')
            ->namespace('App\Http\Controllers')
            ->group(base_path('vendor/tcg/voyager/routes/voyager.php'));
    }*/
}
